### ISSUE TITLE
Documentation incorrect for slice of SortedSet

### ISSUE THREAD

**Issue by fgregg** [grantjenks/sorted_containers#72]
According to this documentation: http://www.grantjenks.com/docs/sortedcontainers/sortedset.html

The slice of a SortedSet returns a SortedSet

```python
>>> foo = SortedSet(range(10))
>>> foo
SortedSet([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], key=None, load=1000)
>>> foo[2:5]
[2, 3, 4]
```

but that is not what the current version of sortedcontainers' SortedSet does.

**Comment by PaulRudin** [comment]
Is this a documentation issue or a implementation issue? Returning a SortedSet feels like the more natural thing.

**Comment by grantjenks** [comment]
Documentation issue. Suppose the step is -1 like sorted_set[2:9:-1] then we can't return a sorted set.

**Comment by mgdelmonte** [comment]
Would be nice to fix either the code or the documentation.  If the code supports only S[i:j] with no step then you could still return a SortedSet.  The docs definitely suggest otherwise and I got burned by relying on the documentation for production code.  If the code isn't changed, then definitely change the docs, please.

**Comment by grantjenks** [comment]
Pull request welcome for docs.

**Comment by grantjenks** [comment]
Fixed in V2, coming later this May.
