### ISSUE TITLE
SortedDict Question: slicing keys-value pairs?

### ISSUE THREAD

**Issue by icefoxen** [grantjenks/sorted_containers#80]
Sorry if this has an obvious solution, I'm using SortedDict to implement a timeseries collection with times as keys and values as, well, values.  A very common operation is testing whether a value exists within a certain time range, so I need iterator over `(key, value)` pairs within a certain range of keys.  Right now I'm doing this with `((t,chan[t]) for t in chan.irange(t0, t1))` but it seems like there should be a built-in method that is faster.  Does this exist and I'm missing it?

Thanks in advance.

**Comment by grantjenks** [comment]
Happy to help. You're doing it right. SortedDict maintains two objects internally:
a dictionary mapping keys to values and a SortedList index maintaining the key's sort order. When you lookup ``chan.irange(t0, t1)``, you're using the SortedList index to bisect for the desired keys. You then need to map those keys to values using the dictionary with ``chan[t]``.

```python
In [1]: import sortedcontainers as sc
In [2]: from random import random
In [3]: sd = sc.SortedDict((random(), count) for count in range(1_000))
In [6]: list((key, sd[key]) for key in sd.irange(0.1, 0.11))
Out[6]: 
[(0.10014260545026188, 250),
 (0.10025478511913155, 164),
 (0.10167864888439537, 53),
 (0.1029894710341761, 961),
 (0.10337150375335602, 286),
 (0.10577389709115703, 190),
 (0.10578348322597375, 869),
 (0.1065580047638568, 363),
 (0.1096326237566907, 878)]

In [9]: %timeit list((key, sd[key]) for key in sd.irange(0.1, 0.11))
4.95 µs ± 80.8 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
```

An alternative implementation would store ``(key, value)`` pairs directly in a SortedList. Since your keys are unique, your values would not need to be orderable (or could rely on an ordering based on ``id(value)``). This would accelerate range queries where you needed the value.

```python
In [7]: sl = sc.SortedList((random(), count) for count in range(1_000))
In [8]: list(sl.irange((0.1, 0), (0.11, 0)))
Out[8]: 
[(0.10004762396603673, 980),
 (0.10020713170507256, 502),
 (0.1019409939392465, 977),
 (0.10306030304431646, 716),
 (0.10343305019242544, 319),
 (0.10395577257364563, 439),
 (0.10401676982305841, 5),
 (0.10514110441566027, 633),
 (0.10675560706552867, 254),
 (0.10897799664886043, 261),
 (0.10958796583832975, 216)]

In [10]: %timeit list(sl.irange((0.1, 0), (0.11, 0)))
3.02 µs ± 34.6 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
```

But this would also slow down value-lookups given just a key.
