### ISSUE TITLE
SortedDict - sort by value

### ISSUE THREAD

**Issue by bdueck** [grantjenks/sorted_containers#82]
SortedDict constructor allows for a sort key function to be provided, however this sort key function only provides one argument - the key itself. 

A desirable enhancement would be to support an alternate signature for the sort key function which provides both the key and value.  This would enable sorting of the list by value as well as key.

If there's a way to do this today, I'd love to hear about it. If not - any plans on making this an enhancement in the future?

Of course users would need to be aware of side effects - making changes to the value in a way such that the SortedDict is unaware. Not a problem for atomic types - but could be a problem for more complex objects if there is a reference to them elsewhere that is changing them. But this could be remedied by simply having the client updated the SortedDict using the same key and new value.

**Comment by grantjenks** [comment]
I’m at the gym which makes a longer response difficult but yes, what you want exists in another package. Check out sortedcollections

**Comment by bdueck** [comment]
Thanks Grant and sorry to interrupt your workout.

I found sortedcollections.ValueSortedDict referenced in another issue post just after I wrote the above. Have been playing with it and seems to do the job - great work and thank you!

Appreciate the quick response - now off to burn some calories myself!

**Comment by scls19fr** [comment]
I was wondering same question (because I didn't find information in doc)...
While I was writing title for a new issue, I saw this issue... 
Maybe improving doc should be considered?
I'm willing to provide PR if you find it can be a good idea (and if you are willing to provide some guidance ie which file should be modified, if docstring in source and/or if reStructuredText doc file should be modified)
